### ISSUE TITLE
 Cannot read property 'dedent' of undefined when using with tslint 5.10

### ISSUE THREAD

**Issue by nosus** [kwonoj/tslint-no-unused-expression-chai#16]
I get the following error
```
TypeError: Cannot read property 'dedent' of undefined
    at Object.<anonymous> (/Users/Erik/Development/Workspace_Dxnext/prod-authoring-ui/node_modules/tslint-no-unused-expression-chai/rules/noUnusedExpressionChaiRule.js:30:1036)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at loadRule (/Users/Erik/.nvm/versions/node/v6.12.0/lib/node_modules/tslint/lib/ruleLoader.js:102:12)
    at loadCachedRule (/Users/Erik/.nvm/versions/node/v6.12.0/lib/node_modules/tslint/lib/ruleLoader.js:119:16)
```

my tslint file: 
```
{
  "rules": {
    "class-name": true,
    "comment-format": [true, "check-space"],
    "curly": true,
    "eofline": true,
    "forin": true,
    "indent": [true, "spaces"],
    "label-position": true,
    "max-line-length": [true, 200],
    "member-access": true,
    "member-ordering": [true,
      "public-before-private",
      "static-before-instance",
      "variables-before-functions"
    ],
    "no-arg": true,
    "no-bitwise": true,
    "no-console": [true,
      "debug",
      "info",
      "time",
      "timeEnd",
      "trace"
    ],
    "no-construct": true,
    "no-debugger": true,
    "no-duplicate-variable": true,
    "no-empty": true,
    "no-eval": true,
    "no-inferrable-types": true,
    "no-shadowed-variable": true,
    "no-string-literal": true,
    "no-switch-case-fall-through": true,
    "no-trailing-whitespace": true,
//    "no-unused-expression": true,
    "no-unused-expression-chai": true,
    "no-unused-variable": true,
    "no-use-before-declare": true,
    "no-var-keyword": true,
    "object-literal-sort-keys": false,
    "one-line": [true,
      "check-open-brace",
      "check-catch",
      "check-else",
      "check-finally",
      "check-whitespace"
    ],
    "quotemark": [true, "double", "avoid-escape"],
    "radix": true,
    "semicolon": [true, "always"],
    "trailing-comma": [true, {
      "singleline": "never",
      "multiline": "never"
    }],
    "triple-equals": [true, "allow-null-check"],
    "typedef-whitespace": [true, {
      "call-signature": "nospace",
      "index-signature": "nospace",
      "parameter": "nospace",
      "property-declaration": "nospace",
      "variable-declaration": "nospace"
    }],
    "variable-name": false,
    "whitespace": [true,
      "check-branch",
      "check-decl",
      "check-operator",
      "check-separator",
      "check-type"
    ]
  },
  "rulesDirectory": [
    "tslint-no-unused-expression-chai"
  ]
}
```

**Comment by nosus** [comment]
sorry, false alarm.

**Comment by kwonoj** [comment]
Tried with one of my codebases but doesn't seem to have same issue. If you can, please create small repo able to reproduce issue to find out cause.

**Comment by kwonoj** [comment]
Closing as deprecated https://github.com/kwonoj/tslint-no-unused-expression-chai/pull/22 .
